const BATTLE_SHIP = 1
const CRUISER = 2
const DESTROYER = 3
const SUBMARINE = 4

const BATTLE_SHIP_SIZE = 4
const CRUISER_SIZE = 3
const DESTROYER_SIZE = 3
const SUBMARINE_SIZE = 2

const BATTLE_SHIP_COUNT = 1
const CRUISER_COUNT = 2
const DESTROYER_COUNT = 3
const SUBMARINE_COUNT = 4

const VERTICAL = 'V'
const HORIZONTAL = 'H'

const BOARD_SIZE = 10

export {
  BATTLE_SHIP,
  CRUISER,
  DESTROYER,
  SUBMARINE,
  
  BATTLE_SHIP_SIZE,
  CRUISER_SIZE,
  DESTROYER_SIZE,
  SUBMARINE_SIZE,
  
  BATTLE_SHIP_COUNT,
  CRUISER_COUNT,
  DESTROYER_COUNT,
  SUBMARINE_COUNT,

  VERTICAL,
  HORIZONTAL,

  BOARD_SIZE
}