const BATTLE_SHIP_SIZE = 1
const CRUISER_SIZE = 0
const DESTROYER_SIZE = 0
const SUBMARINE_SIZE = 0

const BATTLE_SHIP_COUNT = 2
const CRUISER_COUNT = 0
const DESTROYER_COUNT = 0
const SUBMARINE_COUNT = 0

const BOARD_SIZE = 3

export {
  BATTLE_SHIP_SIZE,
  CRUISER_SIZE,
  DESTROYER_SIZE,
  SUBMARINE_SIZE,
  
  BATTLE_SHIP_COUNT,
  CRUISER_COUNT,
  DESTROYER_COUNT,
  SUBMARINE_COUNT,

  BOARD_SIZE
}
