
//general
const NO_BOARD = 10
const ACTION_NOT_ALLOWED = 11

//placing
const NO_SHIP = 20
const SHIP_EXCEED_BOARD_SIZE = 21
const SHIP_OVERLAP = 22

//attacking
const ALREADY_ATTACKED = 30
const ATTACK_POSITION_EXCEED_BOARD_SIZE = 31

export {
  NO_BOARD,
  ACTION_NOT_ALLOWED,
  NO_SHIP,
  SHIP_EXCEED_BOARD_SIZE,
  SHIP_OVERLAP,
  ALREADY_ATTACKED,
  ATTACK_POSITION_EXCEED_BOARD_SIZE
}
